### ISSUE TITLE
InvocationTargetException crashes

### ISSUE THREAD

**Issue by Badrinathjanghel** [ImaginativeShohag/Why-Not-Image-Carousel#72]
Crashes on open with InvocationTargetException Error for view 
    Process: com.team.shareware, PID: 29716

    android.view.InflateException: Binary XML file line #57 in com.team.shareware:layout/product_card_layout: Binary XML file line #57 in com.team.shareware:layout/product_card_layout: Error inflating class org.imaginativeworld.whynotimagecarousel.ImageCarousel
    Caused by: android.view.InflateException: Binary XML file line #57 in com.team.shareware:layout/product_card_layout: Error inflating class org.imaginativeworld.whynotimagecarousel.ImageCarousel
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)

**Comment by ImaginativeShohag** [comment]
Need more information. If possible please give your layout XML and initialization code.
